
project_id = "wntmgfuclbdrezxcvzmw"

[api]
enabled = true

[api.serve]
enabled = true
protocol = "ws"

[db]
enabled = true

[functions]
enabled = true

[functions.delete-document]
verify_jwt = true

[functions.delete-document-version]
verify_jwt = true

[functions.delete-comment]
verify_jwt = true

[functions.verify-invitation-token]
verify_jwt = false

[functions.accept-invitation]
verify_jwt = true

[functions.delete-milestone]
verify_jwt = true

[functions.document-ai-assistant]
verify_jwt = true

[functions.invite-participant]
verify_jwt = true

[functions.remove-participant]
verify_jwt = true

[functions.update-milestone-status]
verify_jwt = true

[realtime]
enabled = false

[storage]
enabled = false
