project_id = "wntmgfuclbdrezxcvzmw"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54324

[inbucket]
enabled = true
port = 54325

[storage]
enabled = true
port = 54326

[auth]
enabled = true
port = 54327

[edge_runtime]
enabled = true
port = 54329

[functions.verify-invitation-token]
verify_jwt = false

[functions.decline-invitation]
verify_jwt = false

[functions.invite-participant]
verify_jwt = true