
# This is an example supabase/config.toml for configuring edge functions

project_id = "wntmgfuclbdrezxcvzmw"

[functions."document-ai-assistant"]
verify_jwt = true

[functions."text-extractor"]
verify_jwt = false

[[functions.import_map.imports]]
name = "std/server"
path = "https://deno.land/std@0.170.0/http/server.ts"
